// Muscle regions shown on the figure. `views` marks which side of the body the
// region is visible from, so the renderer knows where to paint each score.
//
// Groups are split only where a real programming choice turns on it, and always
// by joint action rather than by region of a single muscle: the chest by humeral
// angle, the triceps long head because it crosses the shoulder, gastrocnemius
// and soleus because one crosses the knee and the other does not.
const MUSCLES = [
  { id: 'neck',            name: 'Neck',                     region: 'Upper body',   views: ['front', 'back'] },
  { id: 'trapsUpper',      name: 'Upper traps',              region: 'Upper body',   views: ['front', 'back'] },
  { id: 'trapsMid',        name: 'Mid back',                 region: 'Upper body',   views: ['back'] },
  { id: 'lats',            name: 'Lats',                     region: 'Upper body',   views: ['front', 'back'] },
  { id: 'chestUpper',      name: 'Upper chest',              region: 'Upper body',   views: ['front'] },
  { id: 'chestLower',      name: 'Mid & lower chest',        region: 'Upper body',   views: ['front'] },
  { id: 'deltFront',       name: 'Front delts',              region: 'Shoulders',    views: ['front'] },
  { id: 'deltSide',        name: 'Side delts',               region: 'Shoulders',    views: ['front', 'back'] },
  { id: 'deltRear',        name: 'Rear delts',               region: 'Shoulders',    views: ['back'] },
  { id: 'biceps',          name: 'Biceps',                   region: 'Arms',         views: ['front'] },
  { id: 'tricepsLong',     name: 'Triceps, long head',       region: 'Arms',         views: ['back'] },
  { id: 'tricepsLateral',  name: 'Triceps, lateral heads',   region: 'Arms',         views: ['back'] },
  { id: 'forearms',        name: 'Forearms & grip',          region: 'Arms',         views: ['front', 'back'] },
  { id: 'abs',             name: 'Abs',                      region: 'Trunk',        views: ['front'] },
  { id: 'obliques',        name: 'Obliques',                 region: 'Trunk',        views: ['front', 'back'] },
  { id: 'erectors',        name: 'Lower back',               region: 'Trunk',        views: ['back'] },
  { id: 'glutes',          name: 'Glutes',                   region: 'Legs',         views: ['back'] },
  { id: 'quads',           name: 'Quads',                    region: 'Legs',         views: ['front'] },
  { id: 'hamstrings',      name: 'Hamstrings',               region: 'Legs',         views: ['back'] },
  { id: 'adductors',       name: 'Inner thighs',             region: 'Legs',         views: ['front'] },
  { id: 'abductors',       name: 'Hip abductors',            region: 'Legs',         views: ['back'] },
  { id: 'gastroc',         name: 'Calves, gastrocnemius',    region: 'Legs',         views: ['front', 'back'] },
  { id: 'soleus',          name: 'Calves, soleus',           region: 'Legs',         views: ['front', 'back'] },
];

const MUSCLE_BY_ID = Object.fromEntries(MUSCLES.map((m) => [m.id, m]));

// Activation weights per exercise, 0-1 per muscle.
//   1.00  prime mover
//   0.50  meaningful assistance
//   0.25  stabiliser / isometric hold
const EXERCISES = [
  // ---- Chest ----
  { id: 'bench-press', name: 'Barbell bench press', group: 'Chest', gear: 'Barbell',
    m: { chestLower: 1, deltFront: .6, tricepsLateral: .55, chestUpper: .5, tricepsLong: .4,
         trapsMid: .15, abs: .1 } },
  { id: 'incline-bench', name: 'Incline bench press', group: 'Chest', gear: 'Barbell',
    m: { chestUpper: 1, deltFront: .8, chestLower: .5, tricepsLateral: .5, tricepsLong: .4,
         trapsUpper: .1 } },
  { id: 'decline-bench', name: 'Decline bench press', group: 'Chest', gear: 'Barbell',
    m: { chestLower: 1, tricepsLateral: .5, deltFront: .35, tricepsLong: .35, chestUpper: .2 } },
  { id: 'db-bench', name: 'Dumbbell bench press', group: 'Chest', gear: 'Dumbbell',
    m: { chestLower: 1, deltFront: .55, chestUpper: .5, tricepsLateral: .45, tricepsLong: .35,
         forearms: .15 } },
  { id: 'db-fly', name: 'Dumbbell fly', group: 'Chest', gear: 'Dumbbell',
    m: { chestLower: .95, chestUpper: .45, deltFront: .3, biceps: .1 } },
  { id: 'cable-crossover', name: 'Cable crossover', group: 'Chest', gear: 'Cable',
    m: { chestLower: 1, chestUpper: .5, deltFront: .25, abs: .1 } },
  { id: 'push-up', name: 'Push-up', group: 'Chest', gear: 'Bodyweight',
    m: { chestLower: .85, tricepsLateral: .5, chestUpper: .45, deltFront: .45, abs: .35, tricepsLong: .35,
         obliques: .2 } },
  { id: 'chest-dip', name: 'Chest dip', group: 'Chest', gear: 'Bodyweight',
    m: { chestLower: .9, tricepsLateral: .8, tricepsLong: .5, deltFront: .45, chestUpper: .25, abs: .2 } },
  { id: 'machine-press', name: 'Machine chest press', group: 'Chest', gear: 'Machine',
    m: { chestLower: 1, chestUpper: .45, deltFront: .45, tricepsLateral: .45, tricepsLong: .3 } },
  { id: 'pec-deck', name: 'Pec deck', group: 'Chest', gear: 'Machine',
    m: { chestLower: .95, chestUpper: .5, deltFront: .2 } },

  // ---- Back ----
  { id: 'deadlift', name: 'Deadlift', group: 'Back', gear: 'Barbell',
    m: { erectors: 1, glutes: .9, hamstrings: .85, quads: .6, trapsMid: .55, forearms: .5, lats: .5,
         abs: .45, trapsUpper: .4, adductors: .3, gastroc: .2, soleus: .2 } },
  { id: 'rack-pull', name: 'Rack pull', group: 'Back', gear: 'Barbell',
    m: { erectors: .9, glutes: .7, trapsMid: .6, forearms: .5, lats: .45, hamstrings: .4, trapsUpper: .35 } },
  { id: 'pull-up', name: 'Pull-up', group: 'Back', gear: 'Bodyweight',
    m: { lats: 1, biceps: .6, trapsMid: .55, forearms: .45, deltRear: .35, abs: .3, chestLower: .15 } },
  { id: 'chin-up', name: 'Chin-up', group: 'Back', gear: 'Bodyweight',
    m: { lats: .9, biceps: .8, trapsMid: .5, forearms: .45, abs: .3 } },
  { id: 'lat-pulldown', name: 'Lat pulldown', group: 'Back', gear: 'Cable',
    m: { lats: 1, biceps: .55, trapsMid: .5, deltRear: .3, forearms: .3 } },
  { id: 'barbell-row', name: 'Barbell row', group: 'Back', gear: 'Barbell',
    m: { trapsMid: .9, lats: .85, deltRear: .6, erectors: .6, biceps: .5, forearms: .4, hamstrings: .2 } },
  { id: 'db-row', name: 'One-arm dumbbell row', group: 'Back', gear: 'Dumbbell',
    m: { lats: .9, trapsMid: .8, biceps: .5, deltRear: .5, forearms: .35, obliques: .2 } },
  { id: 'cable-row', name: 'Seated cable row', group: 'Back', gear: 'Cable',
    m: { trapsMid: .9, lats: .8, biceps: .5, deltRear: .45, forearms: .3, erectors: .25 } },
  { id: 't-bar-row', name: 'T-bar row', group: 'Back', gear: 'Barbell',
    m: { lats: .85, trapsMid: .85, biceps: .5, deltRear: .5, erectors: .5, forearms: .35 } },
  { id: 'straight-arm-pulldown', name: 'Straight-arm pulldown', group: 'Back', gear: 'Cable',
    m: { lats: .9, trapsMid: .3, tricepsLong: .3, abs: .25, tricepsLateral: .15 } },
  { id: 'shrug', name: 'Shrug', group: 'Back', gear: 'Barbell',
    m: { trapsUpper: 1, trapsMid: .35, forearms: .3, neck: .25 } },
  { id: 'back-extension', name: 'Back extension', group: 'Back', gear: 'Bodyweight',
    m: { erectors: 1, glutes: .7, hamstrings: .6 } },
  { id: 'good-morning', name: 'Good morning', group: 'Back', gear: 'Barbell',
    m: { erectors: .95, hamstrings: .9, glutes: .7, adductors: .2 } },

  // ---- Shoulders ----
  { id: 'overhead-press', name: 'Overhead press', group: 'Shoulders', gear: 'Barbell',
    m: { deltFront: 1, deltSide: .7, tricepsLateral: .6, tricepsLong: .6, trapsUpper: .45, abs: .4,
         erectors: .3, chestUpper: .25, chestLower: .1 } },
  { id: 'db-shoulder-press', name: 'Dumbbell shoulder press', group: 'Shoulders', gear: 'Dumbbell',
    m: { deltFront: .95, deltSide: .75, tricepsLateral: .55, tricepsLong: .55, trapsUpper: .4, abs: .3 } },
  { id: 'arnold-press', name: 'Arnold press', group: 'Shoulders', gear: 'Dumbbell',
    m: { deltFront: .95, deltSide: .8, tricepsLateral: .5, tricepsLong: .5, trapsUpper: .35 } },
  { id: 'lateral-raise', name: 'Lateral raise', group: 'Shoulders', gear: 'Dumbbell',
    m: { deltSide: 1, trapsUpper: .35, deltFront: .2 } },
  { id: 'front-raise', name: 'Front raise', group: 'Shoulders', gear: 'Dumbbell',
    m: { deltFront: 1, deltSide: .3, chestUpper: .2, trapsUpper: .2 } },
  { id: 'rear-delt-fly', name: 'Rear delt fly', group: 'Shoulders', gear: 'Dumbbell',
    m: { deltRear: 1, trapsMid: .6 } },
  { id: 'face-pull', name: 'Face pull', group: 'Shoulders', gear: 'Cable',
    m: { deltRear: 1, trapsMid: .7, trapsUpper: .3, biceps: .2 } },
  { id: 'upright-row', name: 'Upright row', group: 'Shoulders', gear: 'Barbell',
    m: { deltSide: .85, trapsUpper: .8, biceps: .3, deltFront: .3, forearms: .25 } },
  { id: 'handstand-push-up', name: 'Handstand push-up', group: 'Shoulders', gear: 'Bodyweight',
    m: { deltFront: .95, tricepsLong: .8, tricepsLateral: .75, deltSide: .6, abs: .5, trapsUpper: .5 } },

  // ---- Arms ----
  { id: 'barbell-curl', name: 'Barbell curl', group: 'Arms', gear: 'Barbell',
    m: { biceps: 1, forearms: .45, deltFront: .15 } },
  { id: 'db-curl', name: 'Dumbbell curl', group: 'Arms', gear: 'Dumbbell',
    m: { biceps: 1, forearms: .4 } },
  { id: 'hammer-curl', name: 'Hammer curl', group: 'Arms', gear: 'Dumbbell',
    m: { biceps: .9, forearms: .7 } },
  { id: 'preacher-curl', name: 'Preacher curl', group: 'Arms', gear: 'Barbell',
    m: { biceps: 1, forearms: .3 } },
  { id: 'incline-curl', name: 'Incline dumbbell curl', group: 'Arms', gear: 'Dumbbell',
    m: { biceps: 1, forearms: .3, deltFront: .1 } },
  { id: 'concentration-curl', name: 'Concentration curl', group: 'Arms', gear: 'Dumbbell',
    m: { biceps: 1, forearms: .25 } },
  { id: 'triceps-pushdown', name: 'Triceps pushdown', group: 'Arms', gear: 'Cable',
    m: { tricepsLateral: 1, tricepsLong: .55, forearms: .2 } },
  { id: 'skull-crusher', name: 'Skull crusher', group: 'Arms', gear: 'Barbell',
    m: { tricepsLong: .9, tricepsLateral: .75, deltFront: .15 } },
  { id: 'overhead-extension', name: 'Overhead triceps extension', group: 'Arms', gear: 'Dumbbell',
    m: { tricepsLong: 1, tricepsLateral: .6, deltFront: .2, abs: .15 } },
  { id: 'close-grip-bench', name: 'Close-grip bench press', group: 'Arms', gear: 'Barbell',
    m: { tricepsLateral: .95, chestLower: .7, tricepsLong: .6, deltFront: .5, chestUpper: .35 } },
  { id: 'triceps-dip', name: 'Triceps dip', group: 'Arms', gear: 'Bodyweight',
    m: { tricepsLateral: 1, chestLower: .6, tricepsLong: .6, deltFront: .4, abs: .2, chestUpper: .2 } },
  { id: 'wrist-curl', name: 'Wrist curl', group: 'Arms', gear: 'Dumbbell',
    m: { forearms: 1 } },
  { id: 'farmers-walk', name: 'Farmer\'s walk', group: 'Arms', gear: 'Dumbbell',
    m: { forearms: 1, trapsUpper: .7, abs: .55, erectors: .5, obliques: .5, glutes: .4, quads: .35,
         soleus: .35, trapsMid: .3, gastroc: .25 } },

  // ---- Legs ----
  { id: 'back-squat', name: 'Back squat', group: 'Legs', gear: 'Barbell',
    m: { quads: 1, glutes: .85, erectors: .6, adductors: .55, hamstrings: .45, abs: .4, soleus: .3,
         gastroc: .25, trapsMid: .2 } },
  { id: 'front-squat', name: 'Front squat', group: 'Legs', gear: 'Barbell',
    m: { quads: 1, glutes: .7, erectors: .55, abs: .5, adductors: .45, trapsUpper: .25 } },
  { id: 'goblet-squat', name: 'Goblet squat', group: 'Legs', gear: 'Dumbbell',
    m: { quads: .9, glutes: .7, abs: .45, adductors: .4, erectors: .35, deltFront: .25, forearms: .25 } },
  { id: 'leg-press', name: 'Leg press', group: 'Legs', gear: 'Machine',
    m: { quads: 1, glutes: .65, adductors: .4, hamstrings: .3, soleus: .25, gastroc: .15 } },
  { id: 'hack-squat', name: 'Hack squat', group: 'Legs', gear: 'Machine',
    m: { quads: 1, glutes: .6, adductors: .35 } },
  { id: 'bulgarian-split-squat', name: 'Bulgarian split squat', group: 'Legs', gear: 'Dumbbell',
    m: { glutes: .95, quads: .9, abductors: .5, adductors: .45, hamstrings: .4, abs: .3, soleus: .3,
         gastroc: .2 } },
  { id: 'lunge', name: 'Walking lunge', group: 'Legs', gear: 'Dumbbell',
    m: { glutes: .9, quads: .85, abductors: .45, adductors: .4, hamstrings: .4, soleus: .3, abs: .25,
         gastroc: .2 } },
  { id: 'step-up', name: 'Step-up', group: 'Legs', gear: 'Dumbbell',
    m: { glutes: .9, quads: .85, abductors: .35, hamstrings: .35, gastroc: .3, soleus: .25 } },
  { id: 'romanian-deadlift', name: 'Romanian deadlift', group: 'Legs', gear: 'Barbell',
    m: { hamstrings: 1, glutes: .85, erectors: .75, forearms: .35, adductors: .3, trapsMid: .2 } },
  { id: 'leg-curl', name: 'Leg curl', group: 'Legs', gear: 'Machine',
    m: { hamstrings: 1, gastroc: .3, glutes: .15 } },
  { id: 'leg-extension', name: 'Leg extension', group: 'Legs', gear: 'Machine',
    m: { quads: 1 } },
  { id: 'hip-thrust', name: 'Hip thrust', group: 'Legs', gear: 'Barbell',
    m: { glutes: 1, hamstrings: .55, erectors: .3, abs: .25, quads: .2 } },
  { id: 'glute-bridge', name: 'Glute bridge', group: 'Legs', gear: 'Bodyweight',
    m: { glutes: 1, hamstrings: .5, erectors: .25, abs: .2 } },
  { id: 'hip-abduction', name: 'Hip abduction', group: 'Legs', gear: 'Machine',
    m: { abductors: 1, glutes: .6 } },
  { id: 'hip-adduction', name: 'Hip adduction', group: 'Legs', gear: 'Machine',
    m: { adductors: 1, glutes: .2 } },
  { id: 'standing-calf-raise', name: 'Standing calf raise', group: 'Legs', gear: 'Machine',
    m: { gastroc: 1, soleus: .5, hamstrings: .1 } },
  { id: 'seated-calf-raise', name: 'Seated calf raise', group: 'Legs', gear: 'Machine',
    m: { soleus: 1, gastroc: .25 } },
  { id: 'sled-push', name: 'Sled push', group: 'Legs', gear: 'Machine',
    m: { quads: .9, glutes: .85, gastroc: .55, hamstrings: .5, soleus: .45, abs: .4, chestLower: .25,
         deltFront: .25, chestUpper: .15 } },

  // ---- Core ----
  { id: 'plank', name: 'Plank', group: 'Core', gear: 'Bodyweight',
    m: { abs: 1, obliques: .6, deltFront: .35, erectors: .35, glutes: .3, quads: .2, chestLower: .1,
         chestUpper: .1 } },
  { id: 'side-plank', name: 'Side plank', group: 'Core', gear: 'Bodyweight',
    m: { obliques: 1, abs: .5, abductors: .45, deltSide: .4, erectors: .3 } },
  { id: 'hanging-leg-raise', name: 'Hanging leg raise', group: 'Core', gear: 'Bodyweight',
    m: { abs: 1, forearms: .5, obliques: .5, lats: .35, quads: .3, adductors: .2 } },
  { id: 'crunch', name: 'Crunch', group: 'Core', gear: 'Bodyweight',
    m: { abs: 1, obliques: .3, neck: .2 } },
  { id: 'bicycle-crunch', name: 'Bicycle crunch', group: 'Core', gear: 'Bodyweight',
    m: { obliques: 1, abs: .85, quads: .25 } },
  { id: 'russian-twist', name: 'Russian twist', group: 'Core', gear: 'Bodyweight',
    m: { obliques: 1, abs: .7, erectors: .25 } },
  { id: 'ab-rollout', name: 'Ab wheel rollout', group: 'Core', gear: 'Bodyweight',
    m: { abs: 1, obliques: .5, lats: .45, deltFront: .4, erectors: .3, tricepsLong: .3,
         tricepsLateral: .2 } },
  { id: 'cable-woodchop', name: 'Cable woodchop', group: 'Core', gear: 'Cable',
    m: { obliques: 1, abs: .7, deltSide: .35, glutes: .3, erectors: .25 } },
  { id: 'dead-bug', name: 'Dead bug', group: 'Core', gear: 'Bodyweight',
    m: { abs: .9, obliques: .5, quads: .3, erectors: .2 } },
  { id: 'pallof-press', name: 'Pallof press', group: 'Core', gear: 'Cable',
    m: { obliques: .95, abs: .7, deltFront: .3, glutes: .3 } },
  { id: 'hollow-hold', name: 'Hollow hold', group: 'Core', gear: 'Bodyweight',
    m: { abs: 1, obliques: .55, quads: .4, deltFront: .2 } },

  // ---- Full body ----
  { id: 'clean-and-jerk', name: 'Clean & jerk', group: 'Full body', gear: 'Barbell',
    m: { glutes: .85, quads: .85, erectors: .8, trapsUpper: .8, deltFront: .75, hamstrings: .7,
         forearms: .6, gastroc: .6, trapsMid: .6, abs: .55, tricepsLateral: .5, tricepsLong: .5,
         deltSide: .45, soleus: .35 } },
  { id: 'power-clean', name: 'Power clean', group: 'Full body', gear: 'Barbell',
    m: { quads: .85, trapsUpper: .85, erectors: .8, glutes: .8, hamstrings: .7, forearms: .55,
         gastroc: .55, trapsMid: .55, abs: .45, deltFront: .45, soleus: .3 } },
  { id: 'snatch', name: 'Snatch', group: 'Full body', gear: 'Barbell',
    m: { trapsUpper: .85, erectors: .8, glutes: .8, quads: .8, deltFront: .7, deltSide: .7,
         hamstrings: .7, forearms: .6, trapsMid: .6, abs: .55, gastroc: .55, tricepsLateral: .4,
         tricepsLong: .4, soleus: .3 } },
  { id: 'thruster', name: 'Thruster', group: 'Full body', gear: 'Barbell',
    m: { quads: .9, deltFront: .85, glutes: .8, tricepsLateral: .55, tricepsLong: .55, abs: .5,
         deltSide: .5, erectors: .5, trapsUpper: .4 } },
  { id: 'kb-swing', name: 'Kettlebell swing', group: 'Full body', gear: 'Kettlebell',
    m: { glutes: 1, hamstrings: .85, erectors: .7, abs: .5, forearms: .45, deltFront: .35, quads: .3,
         trapsUpper: .25 } },
  { id: 'turkish-get-up', name: 'Turkish get-up', group: 'Full body', gear: 'Kettlebell',
    m: { abs: .8, obliques: .8, deltFront: .7, deltSide: .6, glutes: .6, erectors: .5, quads: .5,
         tricepsLong: .5, tricepsLateral: .45, trapsUpper: .4 } },
  { id: 'burpee', name: 'Burpee', group: 'Full body', gear: 'Bodyweight',
    m: { quads: .7, chestLower: .6, glutes: .6, abs: .55, deltFront: .5, gastroc: .5, tricepsLateral: .5,
         hamstrings: .35, tricepsLong: .35, chestUpper: .3, soleus: .25 } },
  { id: 'rowing-machine', name: 'Rowing machine', group: 'Full body', gear: 'Machine',
    m: { quads: .8, lats: .7, trapsMid: .7, erectors: .6, glutes: .6, hamstrings: .5, biceps: .45,
         abs: .35, forearms: .35, soleus: .3, gastroc: .25 } },
  { id: 'battle-ropes', name: 'Battle ropes', group: 'Full body', gear: 'Machine',
    m: { deltFront: .7, forearms: .7, abs: .5, deltSide: .5, trapsUpper: .4, biceps: .35, obliques: .35,
         tricepsLateral: .35, tricepsLong: .3 } },
  { id: 'sprint', name: 'Sprint', group: 'Full body', gear: 'Bodyweight',
    m: { glutes: .9, gastroc: .85, hamstrings: .85, quads: .8, soleus: .5, abs: .4, erectors: .4,
         deltFront: .2 } },
  { id: 'jump-rope', name: 'Jump rope', group: 'Full body', gear: 'Bodyweight',
    m: { gastroc: 1, soleus: .5, quads: .4, forearms: .3, hamstrings: .3, deltSide: .2 } },
  { id: 'box-jump', name: 'Box jump', group: 'Full body', gear: 'Bodyweight',
    m: { quads: .85, gastroc: .8, glutes: .8, hamstrings: .5, soleus: .4, abs: .3 } },
];

const GROUPS = [...new Set(EXERCISES.map((e) => e.group))];
