// Muscle groups shown on the figure. `views` marks which side of the body the
// region is visible from, so the renderer knows where to paint each score.
const MUSCLES = [
  { id: 'neck',        name: 'Neck',              region: 'Upper body',  views: ['front', 'back'] },
  { id: 'trapsUpper',  name: 'Upper traps',       region: 'Upper body',  views: ['front', 'back'] },
  { id: 'trapsMid',    name: 'Mid back',          region: 'Upper body',  views: ['back'] },
  { id: 'lats',        name: 'Lats',              region: 'Upper body',  views: ['front', 'back'] },
  { id: 'chest',       name: 'Chest',             region: 'Upper body',  views: ['front'] },
  { id: 'deltFront',   name: 'Front delts',       region: 'Shoulders',   views: ['front'] },
  { id: 'deltSide',    name: 'Side delts',        region: 'Shoulders',   views: ['front', 'back'] },
  { id: 'deltRear',    name: 'Rear delts',        region: 'Shoulders',   views: ['back'] },
  { id: 'biceps',      name: 'Biceps',            region: 'Arms',        views: ['front'] },
  { id: 'triceps',     name: 'Triceps',           region: 'Arms',        views: ['back'] },
  { id: 'forearms',    name: 'Forearms & grip',   region: 'Arms',        views: ['front', 'back'] },
  { id: 'abs',         name: 'Abs',               region: 'Trunk',       views: ['front'] },
  { id: 'obliques',    name: 'Obliques',          region: 'Trunk',       views: ['front', 'back'] },
  { id: 'erectors',    name: 'Lower back',        region: 'Trunk',       views: ['back'] },
  { id: 'glutes',      name: 'Glutes',            region: 'Legs',        views: ['back'] },
  { id: 'quads',       name: 'Quads',             region: 'Legs',        views: ['front'] },
  { id: 'hamstrings',  name: 'Hamstrings',        region: 'Legs',        views: ['back'] },
  { id: 'adductors',   name: 'Inner thighs',      region: 'Legs',        views: ['front'] },
  { id: 'abductors',   name: 'Hip abductors',     region: 'Legs',        views: ['back'] },
  { id: 'calves',      name: 'Calves',            region: 'Legs',        views: ['front', 'back'] },
];

const MUSCLE_BY_ID = Object.fromEntries(MUSCLES.map((m) => [m.id, m]));

// Activation weights per exercise, 0-1 per muscle.
//   1.00  prime mover
//   0.50  meaningful assistance
//   0.25  stabiliser / isometric hold
const EXERCISES = [
  // ---- Chest ----
  { id: 'bench-press', name: 'Barbell bench press', group: 'Chest', gear: 'Barbell',
    m: { chest: 1, deltFront: .6, triceps: .55, trapsMid: .15, abs: .1 } },
  { id: 'incline-bench', name: 'Incline bench press', group: 'Chest', gear: 'Barbell',
    m: { chest: .85, deltFront: .8, triceps: .5, trapsUpper: .1 } },
  { id: 'decline-bench', name: 'Decline bench press', group: 'Chest', gear: 'Barbell',
    m: { chest: .95, triceps: .5, deltFront: .35 } },
  { id: 'db-bench', name: 'Dumbbell bench press', group: 'Chest', gear: 'Dumbbell',
    m: { chest: 1, deltFront: .55, triceps: .45, forearms: .15 } },
  { id: 'db-fly', name: 'Dumbbell fly', group: 'Chest', gear: 'Dumbbell',
    m: { chest: .95, deltFront: .3, biceps: .1 } },
  { id: 'cable-crossover', name: 'Cable crossover', group: 'Chest', gear: 'Cable',
    m: { chest: 1, deltFront: .25, abs: .1 } },
  { id: 'push-up', name: 'Push-up', group: 'Chest', gear: 'Bodyweight',
    m: { chest: .85, triceps: .5, deltFront: .45, abs: .35, obliques: .2 } },
  { id: 'chest-dip', name: 'Chest dip', group: 'Chest', gear: 'Bodyweight',
    m: { chest: .9, triceps: .8, deltFront: .45, abs: .2 } },
  { id: 'machine-press', name: 'Machine chest press', group: 'Chest', gear: 'Machine',
    m: { chest: 1, triceps: .45, deltFront: .45 } },
  { id: 'pec-deck', name: 'Pec deck', group: 'Chest', gear: 'Machine',
    m: { chest: 1, deltFront: .2 } },

  // ---- Back ----
  { id: 'deadlift', name: 'Deadlift', group: 'Back', gear: 'Barbell',
    m: { erectors: 1, glutes: .9, hamstrings: .85, quads: .6, trapsMid: .55, lats: .5, forearms: .5, abs: .45, trapsUpper: .4, adductors: .3, calves: .2 } },
  { id: 'rack-pull', name: 'Rack pull', group: 'Back', gear: 'Barbell',
    m: { erectors: .9, glutes: .7, trapsMid: .6, forearms: .5, lats: .45, trapsUpper: .35, hamstrings: .4 } },
  { id: 'pull-up', name: 'Pull-up', group: 'Back', gear: 'Bodyweight',
    m: { lats: 1, biceps: .6, trapsMid: .55, forearms: .45, deltRear: .35, abs: .3, chest: .15 } },
  { id: 'chin-up', name: 'Chin-up', group: 'Back', gear: 'Bodyweight',
    m: { lats: .9, biceps: .8, trapsMid: .5, forearms: .45, abs: .3 } },
  { id: 'lat-pulldown', name: 'Lat pulldown', group: 'Back', gear: 'Cable',
    m: { lats: 1, biceps: .55, trapsMid: .5, forearms: .3, deltRear: .3 } },
  { id: 'barbell-row', name: 'Barbell row', group: 'Back', gear: 'Barbell',
    m: { trapsMid: .9, lats: .85, deltRear: .6, erectors: .6, biceps: .5, forearms: .4, hamstrings: .2 } },
  { id: 'db-row', name: 'One-arm dumbbell row', group: 'Back', gear: 'Dumbbell',
    m: { lats: .9, trapsMid: .8, deltRear: .5, biceps: .5, forearms: .35, obliques: .2 } },
  { id: 'cable-row', name: 'Seated cable row', group: 'Back', gear: 'Cable',
    m: { trapsMid: .9, lats: .8, biceps: .5, deltRear: .45, forearms: .3, erectors: .25 } },
  { id: 't-bar-row', name: 'T-bar row', group: 'Back', gear: 'Barbell',
    m: { trapsMid: .85, lats: .85, deltRear: .5, biceps: .5, erectors: .5, forearms: .35 } },
  { id: 'straight-arm-pulldown', name: 'Straight-arm pulldown', group: 'Back', gear: 'Cable',
    m: { lats: .9, trapsMid: .3, abs: .25, triceps: .2 } },
  { id: 'shrug', name: 'Shrug', group: 'Back', gear: 'Barbell',
    m: { trapsUpper: 1, trapsMid: .35, forearms: .3, neck: .25 } },
  { id: 'back-extension', name: 'Back extension', group: 'Back', gear: 'Bodyweight',
    m: { erectors: 1, glutes: .7, hamstrings: .6 } },
  { id: 'good-morning', name: 'Good morning', group: 'Back', gear: 'Barbell',
    m: { erectors: .95, hamstrings: .9, glutes: .7, adductors: .2 } },

  // ---- Shoulders ----
  { id: 'overhead-press', name: 'Overhead press', group: 'Shoulders', gear: 'Barbell',
    m: { deltFront: 1, deltSide: .7, triceps: .6, trapsUpper: .45, abs: .4, erectors: .3, chest: .2 } },
  { id: 'db-shoulder-press', name: 'Dumbbell shoulder press', group: 'Shoulders', gear: 'Dumbbell',
    m: { deltFront: .95, deltSide: .75, triceps: .55, trapsUpper: .4, abs: .3 } },
  { id: 'arnold-press', name: 'Arnold press', group: 'Shoulders', gear: 'Dumbbell',
    m: { deltFront: .95, deltSide: .8, triceps: .5, trapsUpper: .35 } },
  { id: 'lateral-raise', name: 'Lateral raise', group: 'Shoulders', gear: 'Dumbbell',
    m: { deltSide: 1, trapsUpper: .35, deltFront: .2 } },
  { id: 'front-raise', name: 'Front raise', group: 'Shoulders', gear: 'Dumbbell',
    m: { deltFront: 1, deltSide: .3, trapsUpper: .2, chest: .15 } },
  { id: 'rear-delt-fly', name: 'Rear delt fly', group: 'Shoulders', gear: 'Dumbbell',
    m: { deltRear: 1, trapsMid: .6 } },
  { id: 'face-pull', name: 'Face pull', group: 'Shoulders', gear: 'Cable',
    m: { deltRear: 1, trapsMid: .7, trapsUpper: .3, biceps: .2 } },
  { id: 'upright-row', name: 'Upright row', group: 'Shoulders', gear: 'Barbell',
    m: { deltSide: .85, trapsUpper: .8, biceps: .3, deltFront: .3, forearms: .25 } },
  { id: 'handstand-push-up', name: 'Handstand push-up', group: 'Shoulders', gear: 'Bodyweight',
    m: { deltFront: .95, triceps: .8, deltSide: .6, trapsUpper: .5, abs: .5 } },

  // ---- Arms ----
  { id: 'barbell-curl', name: 'Barbell curl', group: 'Arms', gear: 'Barbell',
    m: { biceps: 1, forearms: .45, deltFront: .15 } },
  { id: 'db-curl', name: 'Dumbbell curl', group: 'Arms', gear: 'Dumbbell',
    m: { biceps: 1, forearms: .4 } },
  { id: 'hammer-curl', name: 'Hammer curl', group: 'Arms', gear: 'Dumbbell',
    m: { biceps: .9, forearms: .7 } },
  { id: 'preacher-curl', name: 'Preacher curl', group: 'Arms', gear: 'Barbell',
    m: { biceps: 1, forearms: .3 } },
  { id: 'incline-curl', name: 'Incline dumbbell curl', group: 'Arms', gear: 'Dumbbell',
    m: { biceps: 1, forearms: .3, deltFront: .1 } },
  { id: 'concentration-curl', name: 'Concentration curl', group: 'Arms', gear: 'Dumbbell',
    m: { biceps: 1, forearms: .25 } },
  { id: 'triceps-pushdown', name: 'Triceps pushdown', group: 'Arms', gear: 'Cable',
    m: { triceps: 1, forearms: .2 } },
  { id: 'skull-crusher', name: 'Skull crusher', group: 'Arms', gear: 'Barbell',
    m: { triceps: 1, deltFront: .15 } },
  { id: 'overhead-extension', name: 'Overhead triceps extension', group: 'Arms', gear: 'Dumbbell',
    m: { triceps: 1, deltFront: .2, abs: .15 } },
  { id: 'close-grip-bench', name: 'Close-grip bench press', group: 'Arms', gear: 'Barbell',
    m: { triceps: .95, chest: .7, deltFront: .5 } },
  { id: 'triceps-dip', name: 'Triceps dip', group: 'Arms', gear: 'Bodyweight',
    m: { triceps: 1, chest: .6, deltFront: .4, abs: .2 } },
  { id: 'wrist-curl', name: 'Wrist curl', group: 'Arms', gear: 'Dumbbell',
    m: { forearms: 1 } },
  { id: 'farmers-walk', name: "Farmer's walk", group: 'Arms', gear: 'Dumbbell',
    m: { forearms: 1, trapsUpper: .7, abs: .55, obliques: .5, erectors: .5, glutes: .4, quads: .35, calves: .3, trapsMid: .3 } },

  // ---- Legs ----
  { id: 'back-squat', name: 'Back squat', group: 'Legs', gear: 'Barbell',
    m: { quads: 1, glutes: .85, erectors: .6, adductors: .55, hamstrings: .45, abs: .4, calves: .3, trapsMid: .2 } },
  { id: 'front-squat', name: 'Front squat', group: 'Legs', gear: 'Barbell',
    m: { quads: 1, glutes: .7, erectors: .55, abs: .5, adductors: .45, trapsUpper: .25 } },
  { id: 'goblet-squat', name: 'Goblet squat', group: 'Legs', gear: 'Dumbbell',
    m: { quads: .9, glutes: .7, abs: .45, adductors: .4, erectors: .35, deltFront: .25, forearms: .25 } },
  { id: 'leg-press', name: 'Leg press', group: 'Legs', gear: 'Machine',
    m: { quads: 1, glutes: .65, adductors: .4, hamstrings: .3, calves: .2 } },
  { id: 'hack-squat', name: 'Hack squat', group: 'Legs', gear: 'Machine',
    m: { quads: 1, glutes: .6, adductors: .35 } },
  { id: 'bulgarian-split-squat', name: 'Bulgarian split squat', group: 'Legs', gear: 'Dumbbell',
    m: { glutes: .95, quads: .9, abductors: .5, adductors: .45, hamstrings: .4, abs: .3, calves: .25 } },
  { id: 'lunge', name: 'Walking lunge', group: 'Legs', gear: 'Dumbbell',
    m: { glutes: .9, quads: .85, abductors: .45, hamstrings: .4, adductors: .4, calves: .25, abs: .25 } },
  { id: 'step-up', name: 'Step-up', group: 'Legs', gear: 'Dumbbell',
    m: { glutes: .9, quads: .85, hamstrings: .35, abductors: .35, calves: .3 } },
  { id: 'romanian-deadlift', name: 'Romanian deadlift', group: 'Legs', gear: 'Barbell',
    m: { hamstrings: 1, glutes: .85, erectors: .75, forearms: .35, adductors: .3, trapsMid: .2 } },
  { id: 'leg-curl', name: 'Leg curl', group: 'Legs', gear: 'Machine',
    m: { hamstrings: 1, calves: .3, glutes: .15 } },
  { id: 'leg-extension', name: 'Leg extension', group: 'Legs', gear: 'Machine',
    m: { quads: 1 } },
  { id: 'hip-thrust', name: 'Hip thrust', group: 'Legs', gear: 'Barbell',
    m: { glutes: 1, hamstrings: .55, erectors: .3, abs: .25, quads: .2 } },
  { id: 'glute-bridge', name: 'Glute bridge', group: 'Legs', gear: 'Bodyweight',
    m: { glutes: 1, hamstrings: .5, erectors: .25, abs: .2 } },
  { id: 'hip-abduction', name: 'Hip abduction', group: 'Legs', gear: 'Machine',
    m: { abductors: 1, glutes: .6 } },
  { id: 'hip-adduction', name: 'Hip adduction', group: 'Legs', gear: 'Machine',
    m: { adductors: 1, glutes: .2 } },
  { id: 'standing-calf-raise', name: 'Standing calf raise', group: 'Legs', gear: 'Machine',
    m: { calves: 1, hamstrings: .1 } },
  { id: 'seated-calf-raise', name: 'Seated calf raise', group: 'Legs', gear: 'Machine',
    m: { calves: 1 } },
  { id: 'sled-push', name: 'Sled push', group: 'Legs', gear: 'Machine',
    m: { quads: .9, glutes: .85, calves: .6, hamstrings: .5, abs: .4, chest: .25, deltFront: .25 } },

  // ---- Core ----
  { id: 'plank', name: 'Plank', group: 'Core', gear: 'Bodyweight',
    m: { abs: 1, obliques: .6, deltFront: .35, erectors: .35, glutes: .3, quads: .2, chest: .15 } },
  { id: 'side-plank', name: 'Side plank', group: 'Core', gear: 'Bodyweight',
    m: { obliques: 1, abs: .5, abductors: .45, deltSide: .4, erectors: .3 } },
  { id: 'hanging-leg-raise', name: 'Hanging leg raise', group: 'Core', gear: 'Bodyweight',
    m: { abs: 1, obliques: .5, forearms: .5, lats: .35, quads: .3, adductors: .2 } },
  { id: 'crunch', name: 'Crunch', group: 'Core', gear: 'Bodyweight',
    m: { abs: 1, obliques: .3, neck: .2 } },
  { id: 'bicycle-crunch', name: 'Bicycle crunch', group: 'Core', gear: 'Bodyweight',
    m: { obliques: 1, abs: .85, quads: .25 } },
  { id: 'russian-twist', name: 'Russian twist', group: 'Core', gear: 'Bodyweight',
    m: { obliques: 1, abs: .7, erectors: .25 } },
  { id: 'ab-rollout', name: 'Ab wheel rollout', group: 'Core', gear: 'Bodyweight',
    m: { abs: 1, obliques: .5, lats: .45, deltFront: .4, erectors: .3, triceps: .25 } },
  { id: 'cable-woodchop', name: 'Cable woodchop', group: 'Core', gear: 'Cable',
    m: { obliques: 1, abs: .7, deltSide: .35, glutes: .3, erectors: .25 } },
  { id: 'dead-bug', name: 'Dead bug', group: 'Core', gear: 'Bodyweight',
    m: { abs: .9, obliques: .5, quads: .3, erectors: .2 } },
  { id: 'pallof-press', name: 'Pallof press', group: 'Core', gear: 'Cable',
    m: { obliques: .95, abs: .7, deltFront: .3, glutes: .3 } },
  { id: 'hollow-hold', name: 'Hollow hold', group: 'Core', gear: 'Bodyweight',
    m: { abs: 1, obliques: .55, quads: .4, deltFront: .2 } },

  // ---- Full body ----
  { id: 'clean-and-jerk', name: 'Clean & jerk', group: 'Full body', gear: 'Barbell',
    m: { quads: .85, glutes: .85, trapsUpper: .8, erectors: .8, deltFront: .75, hamstrings: .7, calves: .6, forearms: .6, trapsMid: .6, abs: .55, triceps: .5, deltSide: .45 } },
  { id: 'power-clean', name: 'Power clean', group: 'Full body', gear: 'Barbell',
    m: { trapsUpper: .85, quads: .85, glutes: .8, erectors: .8, hamstrings: .7, trapsMid: .55, calves: .55, forearms: .55, deltFront: .45, abs: .45 } },
  { id: 'snatch', name: 'Snatch', group: 'Full body', gear: 'Barbell',
    m: { trapsUpper: .85, quads: .8, glutes: .8, erectors: .8, hamstrings: .7, deltSide: .7, deltFront: .7, trapsMid: .6, forearms: .6, abs: .55, calves: .55, triceps: .4 } },
  { id: 'thruster', name: 'Thruster', group: 'Full body', gear: 'Barbell',
    m: { quads: .9, deltFront: .85, glutes: .8, triceps: .55, deltSide: .5, abs: .5, erectors: .5, trapsUpper: .4 } },
  { id: 'kb-swing', name: 'Kettlebell swing', group: 'Full body', gear: 'Kettlebell',
    m: { glutes: 1, hamstrings: .85, erectors: .7, abs: .5, forearms: .45, deltFront: .35, quads: .3, trapsUpper: .25 } },
  { id: 'turkish-get-up', name: 'Turkish get-up', group: 'Full body', gear: 'Kettlebell',
    m: { obliques: .8, abs: .8, deltFront: .7, deltSide: .6, glutes: .6, quads: .5, erectors: .5, triceps: .45, trapsUpper: .4 } },
  { id: 'burpee', name: 'Burpee', group: 'Full body', gear: 'Bodyweight',
    m: { quads: .7, glutes: .6, chest: .6, abs: .55, triceps: .5, deltFront: .5, calves: .5, hamstrings: .35 } },
  { id: 'rowing-machine', name: 'Rowing machine', group: 'Full body', gear: 'Machine',
    m: { quads: .8, lats: .7, trapsMid: .7, glutes: .6, erectors: .6, hamstrings: .5, biceps: .45, forearms: .35, abs: .35, calves: .3 } },
  { id: 'battle-ropes', name: 'Battle ropes', group: 'Full body', gear: 'Machine',
    m: { deltFront: .7, forearms: .7, deltSide: .5, abs: .5, trapsUpper: .4, biceps: .35, triceps: .35, obliques: .35 } },
  { id: 'sprint', name: 'Sprint', group: 'Full body', gear: 'Bodyweight',
    m: { glutes: .9, hamstrings: .85, calves: .85, quads: .8, abs: .4, erectors: .4, deltFront: .2 } },
  { id: 'jump-rope', name: 'Jump rope', group: 'Full body', gear: 'Bodyweight',
    m: { calves: 1, quads: .4, hamstrings: .3, forearms: .3, deltSide: .2 } },
  { id: 'box-jump', name: 'Box jump', group: 'Full body', gear: 'Bodyweight',
    m: { quads: .85, glutes: .8, calves: .8, hamstrings: .5, abs: .3 } },
];

const GROUPS = [...new Set(EXERCISES.map((e) => e.group))];
